umtc-ym-yip/sn-nodejs-api

- .github/workflows/yaml.yml
- index.js
> 從dev發出pull request 跟main 合併

- .github/workflows/yaml.yml
- index.js
> 將dev的pull request 合併到main 分支觸發runner

- index.js
> [fix/index.js]

- index.js
> [fix/index.js] chi1234567891011

- index.js
> [fix/index.js] chi666

- router/user.js
> [revise/user.js] 增加Token 中的Email欄位

- swagger.yaml
> [revise/user.js,swagger.yaml] 增加Token、swagger 中的Email欄位

- config/database.js
- daily/aoi.js
- index.js
- mssql.js
- mysql.js
> [revise/database.js] Test連線

- router/user.js
- swagger.yaml
> [add/user.js] 新增白名單新增功能

- router/user.js
- swagger.yaml
新增獲取白名單API，LoginIN api 增加白名單輸出
> [add/user.js] 新增獲取白名單API，LoginIN api 增加白名單輸出

- swagger.yaml
> [add/user.js] 修改網址

- index.js
- swagger.yaml
> [revise/user.js,swagger.yaml] 增加本地端和測試環境的選項

- time.js
[revise/time.js]修改convertTimestampToFormattedDate年份問題
> [revise/time.js]修改convertTimestampToFormattedDate年份問題

- index.js
- router/aoi.js
在首頁新增簡易Swagger管理頁面，在Swagger頁面嵌入超連結來切換頁面
> [revise/index.js]在首頁新增簡易Swagger管理頁面，在Swagger頁面嵌入超連結來切換頁面

- api/aoi.yaml
- daily/aoi.js
- index.js
- router/aoi.js
> [revise/aoi.js] 新增lot_type欄位

- api/aoi.yaml
- api/user.yaml
- router/aoi.js
> [revise/aoi.js,aoi.yaml] 新增歷史資料查詢API

- docker-compose.yml
>  [revise/修改docker-compose.yaml] 新增extra_hosts路由映射

- api/aoi.yaml
- router/aoi.js
新增用戶的lot-list的get、post、delete api
> [add/aoi.js,aoi.yaml] 新增用戶的lot-list的get、post、delete api

- api/aoi.yaml
- router/aoi.js
> [add/aoi.js,aoi.yaml] 刪掉aoidaily沒抓到資料 回傳4042k7fu/6dj;4

- router/aoi.js
> [add/aoi.js,aoi.yaml] 忘記在daily抓資料的語法+g;4

- daily/dailyFunc.js
- index.js
- router/aoi.js
> [revise/ aoi.js] 修改process get
